### ISSUE TITLE
Filter to show only products in stock not working correctly

### ISSUE THREAD

**Issue by dogsGhost** [code0wl/react-example-modern-javascript#3]
The checkbox to show only products in stock seems to be doing the opposite of what it should.
Issue appears to be with one of the `if` conditions in `/app/src/components/product-table.jsx` on line 11:

`(product.stocked && inStockOnly)`

If both of these values are `true` then function returns nothing, skipping products in stock and showing those not in stock instead.
Changing this check to `(!product.stocked && inStockOnly)` has the code working correctly for me.

**Comment by code0wl** [comment]
Hey Dogs, I will check this. 
Thanks for reporting!
