### ISSUE TITLE
ERROR in Path must be a string. Received undefined

### ISSUE THREAD

**Issue by stevensacks** [code0wl/react-example-modern-javascript#8]
Clean clone of this repo.

`npm install`

Then

`npm start`

throws the above error.

Going to localhost:8080 shows the same error in the browser.

**Comment by code0wl** [comment]
Hey Steven,

Thanks for reporting. I am not running in this issue. 
Which version of node are you using? 

I have locked the Babel and Webpack versions at a stable release. 
After you pull the project,  remove your node_modules folder and try running 'npm start again'?
Let me know if this helps

My system is running the following
npm 3.3.12
node 5.3.0

**Comment by code0wl** [comment]
After upgrading to node 6.1.0 I am running into the same issue. For it to work properly try using nvm and downgrading your node version for this project. Anything in 5 will work fine.

They have done some major changes in 6. I will fix this. I will also update travis to run with the new node version. 

Thanks for reporting

I see more projects are running into this issue: https://github.com/timoxley/standard-loader/issues/64

**Comment by stevensacks** [comment]
Yes sorry. I am running Node 6.1.0, as well.

**Comment by stevensacks** [comment]
Sorry, I mean 6.2.1. The latest stable build.

**Comment by mauricionr** [comment]
The same error with me!

 Node 6.1.0

**Comment by code0wl** [comment]
Hey everyone, 

if you remove your node_modules folder, pull the latest code from master branch and then run npm install again from your cli. It will work now :)
